---
division:
  strategy: none
variation_attributes:
  - attribute_id: color
    variation_attribute_id: color
    display_value: Color
  - attribute_id: size
    variation_attribute_id: size
    display_value: Size