---
default: &default
  adapter: postgresql
  database: nagual
  host: localhost
  pool: 5
  timeout: 5000
  user: nagual
  password: nagual

development:
  <<: *default

production:
  adapter: 'postgresql'
  pool: 5
  timeout: 5000
  database: <%= ENV['NAGUAL_DATABASE_NAME'] %>
  user: <%= ENV['NAGUAL_DATABASE_USER'] %>
  password: <%= ENV['NAGUAL_DATABASE_PASSWORD'] %>
