---
input:
  csv:
    :col_sep: ','
    :encoding: 'UTF-8'
    :quote_char: '"'
  paths:
    incoming: public/data/incoming
    processing: public/data/processing
    archive: public/data/archive
    error: public/data/error
output:
  path: public/data/output
  error_report:
    path: public/data/reports
    file_prefix: error_report
log:
  file: log/import.log
  date_format: '%Y-%m-%d %H:%M:%S'
  level: INFO
