---
pipeline: import
input:
  csv:
    :col_sep: ','
    :encoding: 'UTF-8'
    :quote_char: '"'
  paths:
    incoming: data/incoming
    processing: data/processing
    archive: data/archive
    error: data/error
output:
  path: data/output
  error_report:
    path: data/reports
    file_prefix: error_report
log:
  file: log/import.log
  date_format: '%Y-%m-%d %H:%M:%S'
  level: INFO
