---
  product:
    mappings:
    - key: id
      to: product_id
    - key: ean
      to: ean
    - key: upc
      to: upc
    - key: unit
      to: unit
    - key: min-order-quantity
      to: min_order_quantity
    - key: step
      to: step_quantity
    - key: name
      to: display_name
    - key: description
      to: short_description
    - key: 'long description'
      to: long_description
    - key: status
      to: online_flag
      name: convert
      params:
        default: 'false'
        values:
          online: 'true'
    - key: from
      to: online_from
      name: date
      params:
        format: '%Y/%m/%d'
    - key: to
      to: online_to
      name: date
      params:
        format: '%Y/%m/%d'
    - key: template
      to: template
    - key: 'tax class id'
      to: tax_class_id
    - key: brand
      to: brand
    - key: manufacturer
      to: manufacturer_name
    - key: SKU
      to: manufacturer_sku
    - key: organization
      to: organization
    - key: master_id
      to: master_product_id
    - key: color
      to: color
    - key: size
      to: size
    - key: stock
      to: stock
    - key: perpetual
      to: perpetual
      name: convert
      params:
        default: 'false'
        values:
          TRUE: 'true'
    - key: price
      to: price
