---
catalog:
  file: catalog.xml
  encoding: UTF-8
  id: nagual-catalog
  xmlns: http://www.demandware.com/xml/impex/catalog/2006-10-31
  header:
    images:
      alt: ${productname}
      title: ${productname}
      base_path: /
      variation_attribute_id: color
      view_types:
        - name: large
          path: 'products/%{master_product_id}_%{variation_value}_%{view_type}.jpg'
        - name: medium
          path: 'products/%{master_product_id}_%{variation_value}_%{view_type}.jpg'
        - name: small
          path: 'products/%{master_product_id}_%{variation_value}_%{view_type}.jpg'
        - name: swatch
          path: 'products/%{master_product_id}_%{variation_value}_%{view_type}.jpg'
inventory:
  file: inventory.xml
  encoding: UTF-8
  id: nagual-catalog
  xmlns: http://www.demandware.com/xml/impex/inventory/2007-05-31
  list_id: inventory
  header:
    default_instock: false
    description: Product Sku inventory
    use_bundle_inventory_only: false
pricebooks:
  file: pricebook.xml
  encoding: UTF-8
  xmlns: http://www.demandware.com/xml/impex/pricebook/2006-10-31
  header:
    pricebook_id: usd-list-prices
    currency: USD
    display_name: List Prices
    online_flag: true
    xml_lang: x-default
  quantity: 1
