default: &default
  adapter: postgresql

development:
  adapter: postgresql
  database: nagual
  host: localhost
  pool: 5
  timeout: 5000
  user: nagual
  password: nagual

test:
  adapter: postgresql
  database: nagual_test
  host: localhost
  pool: 5
  timeout: 5000
  user: nagual
  password: nagual

production:
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: <%= ENV['NAGUAL_DATABASE_NAME'] %>
  user: <%= ENV['NAGUAL_DATABASE_USER'] %>
  password: <%= ENV['NAGUAL_DATABASE_PASSWORD'] %>
