---
input:
  incoming_path: data/incoming
  processing_path: data/processing
  archive_path: data/archive
  error_path: data/error
output:
  xml:
    catalog:
      file: data/catalog.xml
      encoding: UTF-8
      id: nagual-catalog
      xmlns: http://www.demandware.com/xml/impex/catalog/2006-10-31
      images:
        path: /images
        alt: ${productname}
        title: ${productname}
        view_types:
          - large
          - medium
          - small
          - swatch
        extension: jpg
      variation_attribute: color
    inventory:
      file: data/inventory.xml
      encoding: UTF-8
      id: nagual-catalog
      xmlns: http://www.demandware.com/xml/impex/inventory/2007-05-31
      list_id: inventory
      header:
        default_instock: false
        description: Product Sku inventory
        use_bundle_inventory_only: false
    pricebooks:
      file: data/pricebook.xml
      encoding: UTF-8
      xmlns: http://www.demandware.com/xml/impex/pricebook/2006-10-31
      header:
        pricebook_id: usd-list-prices
        currency: USD
        display_name: List Prices
        online_flag: true
        xml_lang: x-default
      quantity: 1

    product:
      lang: x-default
      image: 'images/%{type}/%{id}_%{name}.png'
      variant: '%{name}_%{modifier}'
      variation_attributes:
        - color
        - size
  error_report:
    path: data/reports
    file_prefix: error_report
